function valid = sxgoodfix(latitude, longitude, state)
  valid = (state == 116) ...
        & ~isnan(latitude) & ~isnan(longitude) ...
        & ~(latitude == 0 & longitude == 0);
  valid_indices = find(valid);
  valid(valid_indices(2:end)) = ...
    diff(latitude(valid)) ~= 0 & diff(longitude(valid)) ~= 0; 
end
